// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qinaucdgoehiayzygbyc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFpbmF1Y2Rnb2VoaWF5enlnYnljIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTc3OTI2MzksImV4cCI6MjA3MzM2ODYzOX0.c567tU3MJgEE0QZHN0LmNfQQf6irMpStatYnZoJ7aTo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});